#!/bin/bash

#PBS -l walltime=00:05:00,select=1:ncpus=1:mem=2gb
#PBS -N individual_demo
#PBS -A st-tdjc-1
#PBS -m abe
#PBS -M naitong.chen@stat.ubc.ca
#PBS -o /scratch/st-tdjc-1/naitong-demo/output.txt
#PBS -e /scratch/st-tdjc-1/naitong-demo/error.txt

################################################################################

cd $PBS_O_WORKDIR

julia --project=jlenv -t auto /scratch/st-tdjc-1/naitong-demo/sockeye-demo/job.jl
